version: '3.8'
services:
  redis:
    image: redis:7.0.11-alpine

  djangoweb:
    container_name: webapp
    build:
      context: ./dcelery
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dcelery:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./dcelery
      dockerfile: Dockerfile
    volumes:
      - ./dcelery:/usr/src/app/
    depends_on:
      - redis